version: "3.7"
services:
  db:
    image: postgres:12
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecom
    volumes:
      - ./db-data:/var/lib/postgresql/data

  api:
    env_file:
      - .env
    build:
      context: api
      dockerfile: ../api.dockerfile
    image: ecom/api
    container_name: api
    ports:
      - 8080:8080

    volumes:
      - ./api/src:/home/node/app/src
      - ./api/package.json:/home/node/app/package.json
    depends_on:
      - db
  ui:
    env_file:
      - .env
    build:
      context: ui
      dockerfile: ../ui.dockerfile
    image: ecom/ui
    container_name: ui
    volumes:
      - ./ui/src:/app/src
      - ./ui/package.json:/app/package.json
    ports:
      - 3000:3000
